package com.example.composeswitchcolor.ui.theme.colors.pink
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA0327F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8EB)
val md_theme_light_onPrimaryContainer = Color(0xFF3B002D)
val md_theme_light_secondary = Color(0xFF715765)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBD9EA)
val md_theme_light_onSecondaryContainer = Color(0xFF291521)
val md_theme_light_tertiary = Color(0xFF80543D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onTertiaryContainer = Color(0xFF311303)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1C)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1C)
val md_theme_light_surfaceVariant = Color(0xFFF0DEE5)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4349)
val md_theme_light_outline = Color(0xFF81737A)
val md_theme_light_inverseOnSurface = Color(0xFFF9EEF1)
val md_theme_light_inverseSurface = Color(0xFF342F31)
val md_theme_light_inversePrimary = Color(0xFFFFAEDD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA0327F)
val md_theme_light_outlineVariant = Color(0xFFD3C2C9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFAEDD)
val md_theme_dark_onPrimary = Color(0xFF60004A)
val md_theme_dark_primaryContainer = Color(0xFF821566)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8EB)
val md_theme_dark_secondary = Color(0xFFDEBECE)
val md_theme_dark_onSecondary = Color(0xFF3F2A36)
val md_theme_dark_secondaryContainer = Color(0xFF57404D)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBD9EA)
val md_theme_dark_tertiary = Color(0xFFF4BA9E)
val md_theme_dark_onTertiary = Color(0xFF4B2714)
val md_theme_dark_tertiaryContainer = Color(0xFF653D28)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1C)
val md_theme_dark_onBackground = Color(0xFFEAE0E3)
val md_theme_dark_surface = Color(0xFF1F1A1C)
val md_theme_dark_onSurface = Color(0xFFEAE0E3)
val md_theme_dark_surfaceVariant = Color(0xFF4F4349)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C2C9)
val md_theme_dark_outline = Color(0xFF9C8D93)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1C)
val md_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val md_theme_dark_inversePrimary = Color(0xFFA0327F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFAEDD)
val md_theme_dark_outlineVariant = Color(0xFF4F4349)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF932674)
